# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "events", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "date",        :date
    t.column "space_id",    :integer
  end

  create_table "reservations", :force => true do |t|
    t.column "date",     :date
    t.column "user_id",  :integer
    t.column "space_id", :integer
    t.column "note",     :text
  end

  create_table "resources", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  create_table "resources_spaces", :id => false, :force => true do |t|
    t.column "resource_id", :integer
    t.column "space_id",    :integer
  end

  create_table "seats", :force => true do |t|
    t.column "space_id", :integer
  end

  create_table "spaces", :force => true do |t|
    t.column "name",        :string
    t.column "address",     :string
    t.column "description", :text
    t.column "hours",       :string
    t.column "capacity",    :integer
  end

  create_table "spaces_users", :id => false, :force => true do |t|
    t.column "user_id",  :integer
    t.column "space_id", :integer
    t.column "status",   :string
    t.column "admin",    :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
